### ISSUE TITLE
[Compiling Error] Got the unrecognized status code '404' when downloaded arduino-lib

### ISSUE THREAD

**Issue by jaddel** [syssi/esphome-yeelight-ceiling-light#11]
`--------------------------------------------------------------------------------
Tool Manager: Installing https://github.com/Jason2866/esp32-arduino-lib-builder/raw/framework-arduinoespressif32/framework-arduinoespressif32-release_v3.3-solo1-bd65eb8d1.tar.gz
Error: Got the unrecognized status code '404' when downloaded https://github.com/Jason2866/esp32-arduino-lib-builder/raw/framework-arduinoespressif32/framework-arduinoespressif32-release_v3.3-solo1-bd65eb8d1.tar.gz`

Running the latest esphome in HomeAssistant i'm getting this error trying to upload / update the device.

**Comment by syssi** [comment]
This download isn't available anymore. I will lookup for an alternative.

**Comment by jaddel** [comment]
thank you

**Comment by syssi** [comment]
It looks like the solo1 core cpu is supported official now. I didn't test this change. Could you provide some feedback it's working or not? Thanks in advance!

**Comment by syssi** [comment]
Successfully tested. Works fine!
