### ISSUE TITLE
Yeelight Arwen 450C (YLXD013-B)

### ISSUE THREAD

**Issue by BotoX** [syssi/esphome-yeelight-ceiling-light#22]
Yeelight Arwen Ceiling Light 450C
YLXD013-B
https://en.yeelight.com/product/1383.html
"50W UFC-N Mainboard V02"
"P777 LED DRIVE BOARD"
"WIFI UFC V01"
"UFC RGB V1.0"

Have two of those and am kinda annoyed that they can't get as dark as my older yeelight ceiling lights.
So here are some pictures of it, seems very similar to other supported ones.
https://cloud.botox.bz/s/eFHFLfKRykkm4bJ
To open: Remove single screw in the back and rotate the cover.

Seems to come with dual core ESP32-WROOM-32D (ESP32-D0WD)

Also this project should have a few more infos in the readme:
What works/What doesn't? (I really would like to use the BT remote for example)
How to flash/update?
Revert to original firmware?

**Comment by syssi** [comment]
1. The bluetooth remote is supported if you replace the ESP32 to a dual core version
2. Attach RX, TX, GND and VCC to the ESP32. Pull-down the GPIO0 on boot-up. Flash the esphome yaml.
3. I wasn't able to dump the OEM firmware. At the moment there is no way back.

**Comment by soulcola** [comment]
Is it working with esphome?

**Comment by syssi** [comment]
The device is esp32 based. If somebody identifies the GPIOs it can be used with esphome. I could provide some instructions to get it done if you own a multimeter.

**Comment by ChrisMuc** [comment]
@BotoX How did you open it? Can you tell me, where the clips are located and which tools you used to remove the cover.

@syssi What do you mean with "The bluetooth remote is supported if you replace the ESP32 to a dual core version"? It supports WIFI and Yeelight's bluetooth remote with original firmware. Maybe it's already a dual-core ESP32 inside. Or did someone figure out, that it's just a single-core?

**Comment by syssi** [comment]
In general yeelight safes money by using a single-core ESP32. I haven't seen a yeelight device yet equipped with a dual-core ESP32 by factory. The stock firmware is "optimized" to allow BLE and WiFi coexisting on a single core. ESP-IDF + ESPHome will crash on boot-time if you enable BLE. If you want to use BLE with ESPHome a dual-core ESP32 is required at the moment.

**Comment by syssi** [comment]
> I wasn't able to dump the OEM firmware. At the moment there is no way back.

This isn't true anymore. You should try to dump the flash. I could provide some instructions.

**Comment by stefan0001** [comment]
> This isn't true anymore. You should try to dump the flash. I could provide some instructions.

Hi @syssi  is there something special when creating a backup? 
Found some example for esptool: 
`python ./esptool.py --port /dev/ttyUSB4 --baud 115200 read_flash 0x00000 0x400000 backup.img`
Does this work for yeelight? 


Also thanks for the create work here!

**Comment by syssi** [comment]
Yes! This command will work!

cp. https://github.com/mmakaay/esphome-xiaomi_bslamp2/blob/dev/doc/flashing.md#make-a-backup-of-the-current-firmware

**Comment by marrobHD** [comment]
Did anyone found gpio pins yet? I have the 550C model. If I'm not wrong it has specific LEDs for nightlight?

**Comment by syssi** [comment]
If you provide some high-res photos I could try to help to identify the pins.

**Comment by marrobHD** [comment]
I'll look into it at weekend and try to figure most of it out.

**Comment by syssi** [comment]
You can find some other issues with details about how to identify the correct GPIOs at this project. Good look! Feel free to ask if something is unclear.

**Comment by marrobHD** [comment]
![IMG_20220520_205944](https://user-images.githubusercontent.com/29308361/169594660-0ce86c0b-2106-4097-b40c-f923b88d6308.jpg)
![IMG_20220520_205927](https://user-images.githubusercontent.com/29308361/169594672-cd9185f3-7090-4931-883f-be0027707630.jpg)
![IMG_20220520_205917](https://user-images.githubusercontent.com/29308361/169594677-4a887fb0-66de-4d89-b856-20159827ad07.jpg)

**Comment by syssi** [comment]
You could use a multimeter to measure the continuity between the RX, TX and the GPIO0 pin an the test pins (`TPx`) on the back of the board. If you can find test pins for RX, TX and GPIO0 it's easier to solder.

**Comment by marrobHD** [comment]
I guess there arent any testpoins on the back. There are only 8 pins from the esp going to the mainboard.

**Comment by syssi** [comment]
I'm talking about the back of the small daughter board not the LED driver board. All pins of the ESP should be soldered to the daughter board.

**Comment by syssi** [comment]
`TP3` should be `GPIO0` f.e.

![yeelight-wifi-ufc-v01](https://user-images.githubusercontent.com/2735933/169650680-e82fc7fc-7b44-4e83-bf99-28dbd8ca951a.jpg)

**Comment by marrobHD** [comment]
I found the reason why it didn't work before. I had the wrong esp32 template in front of me. Pinout was different. This matches the esp32 on the board:
![ESP32-Vroom-32D](https://raw.githubusercontent.com/AchimPieters/esp32-homekit-camera/master/Images/ESP32-VROOM-32D-PINOUT.png)

I dumped the firmware and will now try to flash ESPHome.

#### Test points WIFI UFC V01:
TP3 -> GPIO0
TP4 -> GPIO3, RXD0
TP5 -> GPIO1, TXD0
TP1 -> 3V3
TP2 -> GND

**Comment by syssi** [comment]
Good job!

**Comment by marrobHD** [comment]
ESPHome flashed. Everything works, but I also noticed that the network connection is more unstable than with original firmware.

**Comment by syssi** [comment]
My yeelights are pretty stable (1 reconnect per day). Is your access point far away?

![yeelight-wifi](https://user-images.githubusercontent.com/2735933/169701048-e7b4197a-e0ef-468b-9531-50e57200f367.png)

**Comment by syssi** [comment]
This is my wifi config:

```
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  use_address: 192.168.xxx.xxx
  power_save_mode: LIGHT
  reboot_timeout: 5min
```

**Comment by marrobHD** [comment]
AP isn't too far away (-68dBm).
Nevermind, it stopped being unstable. 
![Screenshot_2022-05-22-16-47-31-373-edit_io homeassistant companion android](https://user-images.githubusercontent.com/29308361/169701253-7b4ab41c-7ff0-4b6d-bd07-4a2dfd48443b.jpg)

**Comment by syssi** [comment]
@marrobHD I would like to add your ceiling lamp to the list of supported device. Do you like to contribute your config yaml? Do you know the miio model name (something like `yeelink.light.ceilingXX`)?

**Comment by marrobHD** [comment]
The miio model name is just `yeelight.light.ceilc`.
I used [this](https://github.com/syssi/esphome-yeelight-ceiling-light/blob/main/yeelight_light_ceiling20.yaml)  configuration as base and it almost worked out of the box. Some adjustments were needed to get it working with esp-idf framework.
My config can be found [here](https://gist.github.com/marrobHD/8558c00e97070fcee1f1e5064943e89b).

**Comment by spn91** [comment]
I can confirm that this is also working for the Yeelight Arwen A2001. This is the same light, but without the RGB lights. It is identified as yeelink.light.ceil29.

**Comment by syssi** [comment]
@spn91 Do you own the 50 or 60cm version? I'm asking because of the model identifier. So I can add an question mark to the identifier of the other version.

**Comment by spn91** [comment]
It is the smaller version.

**Comment by slimcdk** [comment]
This also works for the 550S. I have a dump of the original firmwares. Both 2.1.7_0009 and 2.1.7_0011 (this one from the OTA download aswell, but something still seem to be missing). 

I wish to be able to do OTA provision to ESPHome in the future, so I have network traffic captures of the devices as well as decoded mobile app source code, but have not gotten further as of today.

**Comment by DenysShmyhin** [comment]
@slimcdk hi, could you pls share the original dumps for Ceiling Light 550S (YLXD013-A) I'm trying to recover the original firmware after a power outage. Now it is turned into factory mode and all solutions to turn it into default mode didn't work for me (after power on/off it becomes the same factory mode).Thanks in advance

**Comment by maumaumaumaumau** [comment]
I have an issue with connecting the lamp correctly. 
I do exactly as described here: 
TP3 -> GPIO0
TP4 -> GPIO3, RXD0
TP5 -> GPIO1, TXD0
TP1 -> 3V3
TP2 -> GND

additionally I connect GPIO0 to GND, rest is as always: RXD0 -> TXD, TXD0 -> RXD and 3V3 -> 3V3, GND -> GND.

If I turn on the lamp with CH340G or FT232RL WITHOUT USB cable attached, the lamp goes into flash mode. But If I connect the USB Cable to either flashing devices, the lamp shorts (and is dead). What am I doing wrong?

**Comment by syssi** [comment]
Please never power your ceiling lamp using 230VAC if it's open for flashing!! Just power the ESP using 3,3V. As soon the ESP is flashed remove all cables, close the cover and attach the lamp to the ceiling again.

**Comment by maumaumaumaumau** [comment]
FYI: The fuse blew up, I changed it, flashed the lamp. Working like a charm.

**Comment by syssi** [comment]
Good job!

**Comment by helgek** [comment]
> @BotoX How did you open it? Can you tell me, where the clips are located and which tools you used to remove the cover.
> 
> @syssi What do you mean with "The bluetooth remote is supported if you replace the ESP32 to a dual core version"? It supports WIFI and Yeelight's bluetooth remote with original firmware. Maybe it's already a dual-core ESP32 inside. Or did someone figure out, that it's just a single-core?

@BotoX @ChrisMuc I'd also be interested to understand how you can remove the cover. Information on this would be very much appreciated! I'm able to lift a bit the side using a plastic slider but I don't get beyond that.

**Comment by vladimir1vladimirovich** [comment]
Hi there!

I connected to the Xiaomi YLXD013-C (esp32-woom-32d) lamp via UART and tried to upload the program via Arduino IDE, the upload happened, but the terminal said: **“running on single core variant of a chip, but app is built with multi-core support"** and esp kept rebooting all the time.

Please tell me how to flash this esp without using esphome firmware.

P.S. The lamp is planned to be used in OpenHAB.

**Comment by syssi** [comment]
Please give it a try using ESPHome. Just avoid the `api` componnent and use the `mqtt` component to talk to your lamp instead. I assume OpenHAB supports MQTT too.

I don't know how to convince the Arduino IDE to enable the required single core build.

**Comment by rdorsch** [comment]
Does anybody now if the LEDs in the lamp are controlled with a [WS2812B protocol](https://www.arrow.com/en/research-and-events/articles/protocol-for-the-ws2812b-programmable-led)? There are four wires to the lamp PCB, which is one more which is strictly needed fro WS2812B.

**Comment by syssi** [comment]
@rdorsch Why do you think it's WS2812B? IMO the LEDs cannot be controlled individually. You have to control the complete string using PWM.

**Comment by rdorsch** [comment]
I had a LED stripe with WS2812B. But you are right, looking at the PCB it even says VW+, VW-, VC+, VC- for the warm and cold white LEDs.

**Comment by Myakishi** [comment]
Hi.Please share the factory firmware (dump)

**Comment by helgek** [comment]
[fwbackup_Arwen_Bathroom.bin.zip](https://github.com/user-attachments/files/16770534/fwbackup_Arwen_Bathroom.bin.zip)

@Myakishi this is my backup file of the 450C

**Comment by Myakishi** [comment]
Спасибо 28.08.2024, 01:58, "helgek" ***@***.***>***@***.*** this is my backup file of the 450C—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by PsychoRS** [comment]
Hi,

How do you dissassemble the full board of the Arwen 550S from the  case without breaking/desoldering the cable that goes to the leds itself?

**Comment by fir3drag0n** [comment]
> Hi,
> 
> How do you dissassemble the full board of the Arwen 550S from the case without breaking/desoldering the cable that goes to the leds itself? I don't know how to remove the full board (including the ESP32 daughter board) from the lamp case to be able to flash the daughter board...

Did you solve it?

**Comment by PsychoRS** [comment]
> > Hi,
> > How do you dissassemble the full board of the Arwen 550S from the case without breaking/desoldering the cable that goes to the leds itself? I don't know how to remove the full board (including the ESP32 daughter board) from the lamp case to be able to flash the daughter board...
> 
> Did you solve it?

Yes, I finally managed to flash it without removing that cable, just fiddling around and using some PCBite tools to keep the board in the needed position:

![Image](https://github.com/user-attachments/assets/0d8043cb-6fd9-4a0c-8ffb-08e50494f18a)

As you can see, the cable for the ambilight led strip is still connected.

**Comment by slimcdk** [comment]
> > Hi,
> > 
> > How do you dissassemble the full board of the Arwen 550S from the case without breaking/desoldering the cable that goes to the leds itself? I don't know how to remove the full board (including the ESP32 daughter board) from the lamp case to be able to flash the daughter board...
> 
> Did you solve it?

Mine was a single cable that could be unplugged.

**Comment by fir3drag0n** [comment]
Which variant do you own?
