### ISSUE TITLE
webserver component not valid on Yeelight Meteorite with new ESP-IDF framework?

### ISSUE THREAD

**Issue by PsychoRS** [syssi/esphome-yeelight-ceiling-light#28]
Hi,

I'm trying to compile ESPHome firmware for my Meteorite. I'm unable to do it using ESP-IDF framework if I keep the webserver: component.

Is it normal? Does the new ESP-IDF platform support webserver component?

Thanks

**Comment by syssi** [comment]
If a component isn't supported by ESP-IDF you should see a critical error telling the platform "arduino" is supported only.

**Comment by PsychoRS** [comment]
Yes, that's the error I got, just asking if it is normal behaviour.

**Comment by syssi** [comment]
Yes it is. You could use the arduino platform if you want to avoid ESP-IDF:

https://github.com/syssi/esphome-yeelight-ceiling-light/commit/db03752d2354cd0a5aa51fbc723b2520a3e677b0

**Comment by syssi** [comment]
Do you agree to close the issue?

**Comment by PsychoRS** [comment]
Thanks, sorry.

But... the lamp is 100% operative using the older arduino platform instead of the new ESP-IDF?

**Comment by syssi** [comment]
I've asked more or less the same question here: https://github.com/mmakaay/esphome-xiaomi_bslamp2/issues/62
