### ISSUE TITLE
Is it possible to keep the factory firmware?

### ISSUE THREAD

**Issue by chex01** [syssi/esphome-yeelight-ceiling-light#35]
Faced a problem after updating the lamp to version 2.1.7_0028. Yeelight YLXD50YL (yeelink.light.ceiling20) DIED after update.
My topic on the Yeelight forum: [CLICK](https://forum.yeelight.com/t/topic/27862)

If I find a working firmware, I can download the firmware from it and restore a non-working lamp, right? #21

**Comment by syssi** [comment]
If the device isn't physically damaged you can flash this firmware to the ESP. If you own a firmware dump of a second device you could flash the dump to the ESP. Both is possible.

**Comment by syssi** [comment]
How to backup the factory firmware: https://github.com/mmakaay/esphome-xiaomi_bslamp2/blob/dev/doc/flashing.md#make-a-backup-of-the-current-firmware
