### ISSUE TITLE
yeelink.light.ceiling20 vs. yeelink.light.ceiling22

### ISSUE THREAD

**Issue by B48D81EFCC** [syssi/esphome-yeelight-ceiling-light#56]
Hi,

I have a Xiaomi Mi Ceiling Light (this is the name on the box).
Originally the device is made by Yeelight. It seems a re-branded (any maybe slightly modified) version of a Yeelight device.

The hostname / DNS of the light is yeelink-light-ceiling22-mibt1ADB (identifies as ceiling22).
On the device itself I can find two slightly different model no.:
- MJXDD001
- MJXDD01SYL

So far everything looks like it is a **yeelink.light.ceiling22**

BUT
According to your published pinout and the photos it fits more the **YLXD50YL**

So some details suggest it is yeelink.light.ceiling20 and some details suggest it is yeelink.light.ceiling22

What do you think?

**Comment by B48D81EFCC** [comment]
![20220919_180046608_iOS (2)](https://user-images.githubusercontent.com/111175947/191360621-0ce826c9-a265-4b39-a06c-6db6ef857769.jpg)
![20220919_185214988_iOS (2)](https://user-images.githubusercontent.com/111175947/191360654-a7d15a3f-3a9d-45a4-aa16-1fb71be45454.jpg)
![20220919_17
![20220920_202513989_iOS (2)](https://user-images.githubusercontent.com/111175947/191360687-46b30f65-0380-42f7-87b4-4b9d6a020a04.jpg)
5946330_iOS (2)](https://user-images.githubusercontent.com/111175947/191360675-a35c4103-edc4-4770-9f03-2b28864dcf5a.jpg)

**Comment by syssi** [comment]
It looks like both versions uses the same WiFi daughter board. The difference between the two YAML example configuration is the RGB support (ceiling20 = with RGB LEDs, ceiling22 = without RGB LEDs). You should use the `ceiling22` as starting point because your device is CWWW only.

**Comment by syssi** [comment]
Could you provide a photo of your ceiling lamp (LED driver board) without the WiFi daughter board attached? I would like to see the socket labels on the mainboard.

The photo should show something like this:https://raw.githubusercontent.com/syssi/esphome-yeelight-ceiling-light/main/images/ylxd50yl/003.jpg

**Comment by B48D81EFCC** [comment]
Hi,

yes I can and will provide.
But I can tell you already: It looks exactly like your photo and the labels are the same (R G B is on my board as well).

**Comment by syssi** [comment]
Do you agree to add your photos to the project under Apache 2.0 license? The pull request of ceiling22 didn't provide any photos. So that's the chance to illustrate/improve the ceiling22 support.

**Comment by B48D81EFCC** [comment]
Yes, sure. Feel free to add de photos to the project or do you want me to create a PR?

**Comment by syssi** [comment]
I'm happy about a contribution too. :-)

**Comment by syssi** [comment]
Feel free to close this issue as soon your setup is up and running.

**Comment by B48D81EFCC** [comment]
Hi,

with the current documented pinout for ceilling22, I was not able to flash the firmware.
TXD = TP4
RXD = TP5

The correct pinout is
TXD = TP5
RXD = TP3

I will create another PR

**Comment by B48D81EFCC** [comment]
I was able to flash the ceiling22 firmware / configuration.

Looks very well so far! I am very happy.
