### ISSUE TITLE
YLLD01YL dissasembly

### ISSUE THREAD

**Issue by adrez99** [syssi/esphome-yeelight-ceiling-light#61]
I have the Yeelight Floor lamp and would like to convert it to esphome, but I can't figure how to dissasembly it. Does anybody has any clue how to do it? Thanks

**Comment by syssi** [comment]
This device looks like a Staria Bedside Lamp, correct? Please check the underside of the stand. Does it looks like this?

https://raw.githubusercontent.com/syssi/esphome-yeelight-ceiling-light/main/images/ylct02yl/001.jpg

**Comment by adrez99** [comment]
It looks like a larger Staria Bedside Lamp, but it's quite different:
![PXL_20230205_214110203](https://user-images.githubusercontent.com/59739805/216848042-57cf8298-be05-435e-b23d-9d973e0e273d.jpg)

I think the circuit board is inside the lamp, but haven't looked at it anymore.
Thank for your answer anyway

**Comment by syssi** [comment]
If you know the miIO security token you could use `miiocli device info` to retrieve the device info messages. It should expose it's a ESP32 or Mediatek device.
