### ISSUE TITLE
Yeelight Meteorite (ceiling10): replacing board

### ISSUE THREAD

**Issue by PsychoRS** [syssi/esphome-yeelight-ceiling-light#65]
Hi,

Due to poor soldering skills, a friend of mine has burned the board of his Yeelight Meteorite.

Is it possible to replace it with a cheap ESP32-WROOM board? Luckily enough, the Meteorite has the connections for the board labeled into the case. so...

It just wire GND, +5V, PC, PW, NL, R, G, B and ON/OFF to the corresponding GPIO on the cheapo board based on the yaml configuration?

What are the two pins (labeled GND and +50V) for in the OEM board, left side? And the +50V one on the RGB plug at right side?

![006](https://user-images.githubusercontent.com/552514/214115254-0ae3339d-6047-4f5b-8e57-338ff14e7fc5.jpg)

My idea is to replace it with a board like this:
![91KkEpmzuHL _SL1500_](https://user-images.githubusercontent.com/552514/214115998-1e052cfc-8d82-4bbb-90de-9751ef87a078.jpg)

Thanks

**Comment by syssi** [comment]
You could replace the ESP32 of the driver board but it's hard to replace the full driver board because there is an LED driver next to the ESP.

**Comment by syssi** [comment]
Let's call the `GND` and `+50V` pin on the left `input`. The jack on the right is the `output`. I assume each Mosfet is used to drive a color (`R`, `G`, `B`).

**Comment by PsychoRS** [comment]
> Let's call the `GND` and `+50V` pin on the left `input`. The jack on the right is the `output`. I assume each Mosfet is used to drive a color (`R`, `G`, `B`).

Thanks, so It looks that its not possible then...

**Comment by syssi** [comment]
What burned exactly of the driver board?

**Comment by PsychoRS** [comment]
> What burned exactly of the driver board?

Its an assumption, he just stripped the 3.3v track in the back of the board trying to solder the wires to the points for flashing, and now the lamp doesn't work

**Comment by syssi** [comment]
Do you agree to close the issue?
